### ISSUE TITLE
It shows me this on Running "npm i"

### ISSUE THREAD

**Issue by ShubhamJ010** [gupsevopse/visited#1]
```npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /Users/shankaranandjha/visited/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.1.2 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@19.0.1 | darwin | arm64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/shankaranandjha/visited/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/shankaranandjha/visited/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/shankaranandjha/visited/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/shankaranandjha/visited/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/shankaranandjha/visited/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/shankaranandjha/visited/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/shankaranandjha/visited/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.0.1/bin/node" "/Users/shankaranandjha/visited/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/shankaranandjha/visited/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v19.0.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shankaranandjha/.npm/_logs/2022-11-09T11_29_54_065Z-debug-0.log
```

**Comment by Niamor972** [comment]
Maybe you still need this https://stackoverflow.com/questions/23709739/why-does-node-js-need-python
